### ISSUE TITLE
Data set selection in sea-map seems 'stuck' 

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#89] opened 2020-12-09 10:15 UTC
The data set selection in sea-map seems to be broken, looks like its stuck on "mixed".

See https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/217

https://dev.newbridge.solidarityeconomy.coop/map.html

**Comment by dtmakm27** [comment] 2020-12-13 08:53
This is currently blocked by https://github.com/SolidarityEconomyAssociation/sea-map/issues/90

**Comment by ColmMassey** [comment] 2021-01-06 23:17
> This is currently blocked by #90

So this is also working now? Can I test it?

**Comment by ColmMassey** [comment] 2021-01-08 10:19
This is still an issue.

**Comment by ColmMassey** [comment] 2021-01-27 16:51
it is no longer stuck, but I think it may be reloading multiple times??
![Untitled](https://user-images.githubusercontent.com/1162642/106024543-c8ded980-60bf-11eb-8345-8a4d654121f9.png)

**Comment by wu-lee** [comment] 2021-01-27 19:37
There is something weird going on there...

**Comment by wu-lee** [comment] 2021-01-27 22:38
If you look at the output from the SPARQL query for newbridge (follow the link from shipshape), it has lots of duplicates in it...

Checking Virtuoso, I see there are near-duplicate graphs for some of the datasets differing only by a trailing delimiter, i.e. 

- https://dev.lod.coop/sea-lod/newbridge
- https://dev.lod.coop/sea-lod/newbridge/

I've deleted them all and waited for regeneration... the duplicate graphs don't come back. But the duplicate initiatives do.

Experimenting with the SPARQL query for newbridge, it seems to be the `activity` field - those initiatives with multiple activities then get a row for each activity (all other fields duplicated, I think.)  But that field has been in the newbridge `query.txt` since  2020/07/08, so that's not looking like a new thing. Is that deliberate?

Duplicates can also be introduced by switching on and off datasets. I won't be surprised if my attempt to prevent the switch closing the sidebar also lost some sort of reset action, but haven't found it yet.  I see errors in the console which suggests some event handlers for links etc. get broken.

**Comment by wu-lee** [comment] 2021-02-02 22:54
See also #103

**Comment by ColmMassey** [comment] 2021-05-28 15:31
Just taking another look at this, it seems to be behaving even worse than before. I can't seem to select just the Newbridge data at all. This is unusable. It was at least usable not very long ago, even if buggy.

**Comment by wu-lee** [comment] 2021-05-28 15:51
Agreed, although I don't know why it would get worse. You could move it up the priority queue if you like?

**Comment by ColmMassey** [comment] 2021-05-28 16:06
It looks pretty close to the top of the pile. Only other ticket allocated to you that is higher is the ticket writing for murmerations.

**Comment by wu-lee** [comment] 2021-06-23 20:47
Ok, looking at the commit history, testing the sea-map code just before all the ICA vocab stuff was added, and the subsequent 1.x release of sea-map, these multi-dataset bugs (this and #103) look like they're gone.

However, there are *other* problems I can reproduce, exceptions which occur when exercising the sidebar. I think these are the issues which stopped me from declaring this all done, but in effect they are different ones.

Ah... so it's coming back to me a bit.  To replicate the problems, you need to switch datasets, and then select an activity on the sidebar. This selection operation hides pins which don't have that activity, and works fine initially, but after a switch, something is not right and there are null pointer exceptions in the code.

I've deployed the code which I'm referring to here on https://dev.newbridge.solidarityeconomy.coop/ to show what I mean.  If you don't watch for exceptions in the console, it manifests as a selection click on an initiative in the side-bar resulting in the map jumping, but no longer a pin being centered with a pop-up; and the contents of the "activities" directory in the side bar being empty.

**Comment by wu-lee** [comment] 2021-06-25 18:22
I've tracked down a number of problems, this code looks like it was written a bit hastily and not tested at all with multi data sets.

- There are various cached data structures which need to be cleared when the data is reloaded on a switch.
- The sidebar directory doesn't get refreshed if it's opened during the loading delay, so I've added a refresh for that when data load complete
- The loader animation doesn't show when the switch causes a data reload, I've fixed that to show in all reloads, and made the loader text readable.

The result is currently pushed onto the dev server, see what you think @ColmMassey

**Closed** 2021-06-27 20:40 UTC
