### ISSUE TITLE
Review how search fields are working

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#80] opened 2020-11-13 10:38 UTC
Given that we are not using ESSGlobal properly for field names, we need to review how the search function is working. Is the  documentation in 

https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md#searchedfields

up to date. Use ICA map to evaluate.

**Comment by ColmMassey** [comment] 2020-11-25 11:22
@dtmakm27, can you check that the search is working correctly for all the supported fields as you would expect it to, and tha the documentation is up to date?

**Comment by dtmakm27** [comment] 2020-11-26 22:43
@ColmMassey seems to be working as intended, the description is: 

--
A list of fields that are looked at when searching name,uri,within,lat,lng,www,regorg,sameas,desc,street,locality,region,postcode,country,primaryActivity,activity,orgStructure,tel,email
Default values: ["name", "www"] 
-- 


Here's an example of setting search fields in the url:
https://dev.ica.solidarityeconomy.coop/?searchedFields=regorg


Anything in particular that you're looking to set them as?

**Comment by ColmMassey** [comment] 2020-11-27 11:49
Can you confirnm these are bugs?

 - activities does not work - tested with search for _agriculture_
 - regOrg - fails in search for _Mutual Org_ - but works for _mutual_
 - uri fails to find _.com_ _fa_ _far_

What does a search for _within_ do?

Can you explain how caps, whitespace and special characters etc are handled?

**Comment by ColmMassey** [comment] 2020-11-27 13:31
>     * uri fails to find _.com_ _fa_ _far_

I was not checking this correctly, but it's still not performing as I'd expect https://ica.solidarityeconomy.coop/?search=uri seems to behave more like it is searching the name.

**Comment by ColmMassey** [comment] 2020-11-27 13:34
> https://ica.solidarityeconomy.coop/?search=uri 

My typo. Ah. What would be a good way to give error feedback that the url arguments were invalid? uri is working as I would expect it.

**Comment by ColmMassey** [comment] 2020-11-27 15:10
Are the url args case sensitive?

Is regorg the same url arg as orgStructure?

We need a multi argument example too.

**Comment by dtmakm27** [comment] 2020-12-01 21:30
the url parameter for specifying the fields to use in search is searchedFields (not search), meaning that the url would be:
https://dev.ica.solidarityeconomy.coop/?searchedFields=activities
instead of 
https://dev.ica.solidarityeconomy.coop/?search=activities
(comment above mentioned this with examples, but I can see how it can be confusing, we should probably change the naming)



>Can you confirnm these are bugs?


I've ran the tests again with the correct parameter and:

>activities does not work - tested with search for agriculture

Activities searches only secondary activities and excludes primary activities. i.e. in your case you are searching for coops with agriculture as a secondary activity, but there are none that list it as a secondary activity. 
Try looking up edu
https://ica.solidarityeconomy.coop/?searchedFields=activities


> regOrg - fails in search for Mutual Org - but works for mutual


https://ica.solidarityeconomy.coop/?searchedFields=regorg

uri fails to find .com fa far
https://ica.solidarityeconomy.coop/?searchedFields=www
www - is for website
uri - is the unique identifier for the coop (e.g. uri: "https://lod.coop/ica/2124")


What does a search for within do?
within is the approximated location of a coop (generated by our geolocation API)
within: "https://www.openstreetmap.org/?mlat=-30.9450891&mlon=-61.5608072"


> Can you explain how caps, whitespace and special characters etc are handled?



We transform all characters lowercase for the specified fields, we then concatenate those fields. When searching we check if the searched query is included anywhere (no special handling other than that)


multiline example:
https://ica.solidarityeconomy.coop/?searchedFields=regorg,primaryActivity


Potential todo's:
 - add primary activity to activities

**Comment by ColmMassey** [comment] 2020-12-02 11:00
> Activities searches only secondary activities and excludes primary activities. i.e. in your case you are searching for coops with agriculture as a secondary activity, but there are none that list it as a secondary activity.

https://prod.data.solidarityeconomy.coop/ica/100.html

lists Agriculture as a secondary activity

**Comment by ColmMassey** [comment] 2020-12-02 11:15
> https://ica.solidarityeconomy.coop/?searchedFields=regorg
> - fails in search for Mutual Org - but works for mutual

It should produce 3 hits. Okay I've pinned it down. We should be displaying this as _Mutual organisation_ in the ica dialog, but we are not. Let's not change this now, but can you point me to the code where the ica dialog maps the raw data to the tailored ICA titles?

**Comment by ColmMassey** [comment] 2020-12-02 11:18
https://ica.solidarityeconomy.coop/?searchedFields=regorg

Searching for _Coop Promoter/Supporter_ produces no hits.

**Comment by ColmMassey** [comment] 2020-12-02 11:28
> Potential todo's:
> 
>     * add primary activity to activities

I think just changing the name of the variable to from activity to otherActivities

**Comment by ColmMassey** [comment] 2020-12-02 11:31
> I think just changing the name of the variable to from activity to otherActivities

Searching across all activities would just require specifying otherActivities and primaryActivity in the list.

**Comment by ColmMassey** [comment] 2020-12-02 11:32
Just confirming that these text searches don't us sparql in any way.

**Comment by dtmakm27** [comment] 2020-12-02 11:44
> Just confirming that these text searches don't us sparql in any way.


They do not

**Comment by dtmakm27** [comment] 2020-12-02 11:47
> Searching across all activities would just require specifying otherActivities and primaryActivity in the list.



Yes, that would be easiest

**Comment by dtmakm27** [comment] 2020-12-02 11:57
> https://prod.data.solidarityeconomy.coop/ica/100.html
lists Agriculture as a secondary activity



This needs a closer look, i'll check tonight 



> code where the ica dialog maps the raw data to the tailored ICA titles


We have a couple of places that do that, in the Vocabulary when generating the data and in the javascript code which is currently hardcoded i.e. is basically this table: 
ICA10: "Agriculture",
      ICA20: "Dairy",
      ICA30: "Forestry",
      ICA40: "Irrigation",
      ICA50: "Fishing",
      ICA60: "Artisans",
      ICA70: "Construction",
      ICA80: "Industry",
      ICA90: "Manufacturing",
      ICA100: "Mining",
      ICA110: "Professional",
      ICA120: "Service",
      ICA130: "Tourism",
      ICA140: "Financial Services",
      ICA150: "Insurance",
      ICA160: "Education",
      ICA170: "Health",
      ICA180: "Community",
      ICA190: "Social",
      ICA200: "Social Service",
      ICA210: "Housing",
      ICA220: "Transport",
      ICA230: "Utilities",
      ICA240: "Retail",
      ICA250: "Production",
      ICA260: "Wholesale and retail trade",
      ICA270: "Education / health / social work",
      ICA280: "Other services",
      ICA290: "All",

**Comment by ColmMassey** [comment] 2020-12-02 14:05
>We have a couple of places that do that, 

Can you point me to them in the code?

Also where the Organisational Structure VES & Base Membership Type VES are mapped.

**Comment by dtmakm27** [comment] 2020-12-03 00:12
on the activities problem, the string searched for is being properly generated 
searchstr: "WHOLESALE AND RETAIL TRADEUtilitiesIndustryAgricultureFinancial Services"

but for some reason is not matching the search

**Comment by dtmakm27** [comment] 2020-12-05 22:48
found the fix for this. The string generated for searching for multiple secondary activities was not in uppercase.
Will push a fix

**Comment by dtmakm27** [comment] 2020-12-05 23:01
> Can you point me to them in the code?
Also where the Organisational Structure VES & Base Membership Type VES are mapped.



In the sea-map (i.e. javascript website):

    "Organisational Structure": {
      OS10: "Community group (formal or informal)",
      OS20: "Not-for-profit organisation",
      OS30: "Social enterprise",
      OS40: "Charity",
      OS50: "Company (Other)",
      OS60: "Workers co-operative",
      OS70: "Housing co-operative",
      OS80: "Consumer co-operative",
      OS90: "Producer co-operative",
      OS100: "Multi-stakeholder co-operative",
      OS110: "Secondary co-operative",
      OS115: "Co-operative",
      OS120: "Community Interest Company (CIC)",
      OS130: "Community Benefit Society / Industrial and Provident Society (IPS)",
      OS140: "Employee trust",
      OS150: "Self-employed",
      OS160: "Unincorporated",
      OS170: "Mutual",
      OS180: "National apex",
      OS190: "National sectoral federation or union",
      OS200: "Regional, state or provincial level federation or union",
      OS210: "Cooperative group",
      OS220: "Government agency/body",
      OS230: "Supranational",
      OS240: "Cooperative of cooperatives / mutuals"
    },
    "Base Membership Type": {
      BMT10: "Consumer/Users",
      BMT20: "Producers",
      BMT30: "Workers",
      BMT40: "Multi-stakeholders",
      BMT50: "Residents",
      BMT60: "Others"
    }









in the data generation code (i.e. ruby scripts):
  TYPE_TO_ORG_STRUCT = {
    "Coop Promoter/Supporter" => "Company (Other)",
    "Cooperative" => "Co-operative",
    "Mutual organisation" => "Mutual",
    "National apex" => "National apex",
    "National sectoral federation or union" => "National sectoral federation or union",
    "Regional, state or provincial level federation or union" => "Regional, state or provincial level federation or union",
    "Supranational" => "Supranational",
    "Cooperative Group" => "Cooperative group",
    "Government" => "Government agency/body",
    "Cooperative of cooperatives / mutuals" => "Cooperative of cooperatives / mutuals",
  }

  ECONOMIC_ACTIVITY_TO_ACTIVITY = {
    "Education / health / social work" => "Education / health / social work",
    "All" => "All",
    "Financial services" => "Financial Services",
    "Fishing" => "Fishing",
    "Housing" => "Housing",
    "Insurance" => "Insurance",
    "Other services" => "Other services",
    "Wholesale and retail trade" => "Wholesale and retail trade",
    "Agriculture" => "Agriculture",
    "Utilities" => "Utilities",
    "Industry" => "Industry",
  }

  BASE_MEMBERSHIP_TYPE = {
    "Consumer/User coops" => "Consumer/Users",
    "Others" => "Others",
    "Producer coops" => "Producers",
    "Worker coops" => "Workers",
    "Multi-stakeholder coops" => "Multi - stakeholders",
    "Residents" => "Residents",
  }




And there is also the SKOS definitions for the VESs.

**Comment by ColmMassey** [comment] 2020-12-06 19:56
> found the fix for this. The string generated for searching for multiple secondary activities was not in uppercase.
> Will push a fix

Okay. Let me know which version to verify in.

**Comment by ColmMassey** [comment] 2020-12-06 20:03
> > Can you point me to them in the code?
> > Also where the Organisational Structure VES & Base Membership Type VES are mapped.
> 
> In the sea-map (i.e. javascript website):

I meant in the code. 

For example, like using a permalink thus
https://github.com/SolidarityEconomyAssociation/sea-map/blob/58d9e6505112b27491b3ea71c51bfc22ae5fc89d/www/map-app/app/model/sse_initiative.js#L71

**Comment by ColmMassey** [comment] 2020-12-06 20:08
> Same error will be fixed for multiple organisation types. @ColmMassey

Will your fix addess this symptom 

>Searching for Coop Promoter/Supporter produces no hits.

**Comment by ColmMassey** [comment] 2020-12-06 20:09
> I think just changing the name of the variable to from activity to otherActivities

Please make this change in the url argument too. Thanks.

**Comment by dtmakm27** [comment] 2020-12-12 10:33
> I meant in the code.
For example, like using a permalink thus




will do 


>Will your fix addess this symptom
Searching for Coop Promoter/Supporter produces no hits


No, just double checked, Coop Promoter/Supporter is a qualifier rather than an organisation type. To be able to search it, we will have to include "qualifiers" to the parameter. I think keeping it like that without adding special cases for handling would be best 
What are your thoughts?

**Comment by dtmakm27** [comment] 2020-12-13 14:13
In the sea-map (i.e. javascript website):

https://github.com/SolidarityEconomyAssociation/sea-map/blob/58d9e6505112b27491b3ea71c51bfc22ae5fc89d/www/map-app/app/model/sse_initiative.js#L22-L106



in the data generation code (i.e. ruby scripts):


https://github.com/SolidarityEconomyAssociation/open-data/blob/93ec49efb8a4f36db7e3892e99efa9ff2c60dc96/ica/converter#L269-L303


The skos files:
https://github.com/essglobal-linked-open-data/map-sse/blob/extension-test/vocabs/standard/qualifiers.skos
https://github.com/essglobal-linked-open-data/map-sse/blob/extension-test/vocabs/standard/activities-ica.skos




And lastly, some special handling for the ica popup:

https://github.com/SolidarityEconomyAssociation/ica-project/blob/d1114d7c12d6e0ab7fed5cc31349254d9784dadd/config/popup.js#L52-L72

**Comment by dtmakm27** [comment] 2020-12-13 14:56
Changed the field naming and fixed the search for multiple secondary activities / organizational structures here: 

https://dev.ica.solidarityeconomy.coop/?searchedFields=otherActivities,qualifiers

Also revised the documentation: 
https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/CONFIG.md#searchedfields

**Comment by wu-lee** [comment] 2020-12-13 18:28
> Also revised the documentation:

I think you know this - but it's worth emphasising: make sure you don't revise that file directly, as it's autogenerated by [`npm run generate-config-doc`][1] and will be lost next time that runs. Make corrections in the documentation in the source code.

[1]: https://github.com/SolidarityEconomyAssociation/sea-map/blob/master/package.json#L17

**Comment by ColmMassey** [comment] 2020-12-14 21:22
https://ica.solidarityeconomy.coop/?searchedFields=regorg

        fails in search for Mutual Org - but works for mutual

> It should produce 3 hits. Okay I've pinned it down. We should be displaying this as Mutual organisation in the ica dialog, but we are not. Let's not change this now, but can you point me to the code where the ica dialog maps the raw data to the tailored ICA titles?


https://github.com/SolidarityEconomyAssociation/sea-map/blob/58d9e6505112b27491b3ea71c51bfc22ae5fc89d/www/map-app/app/model/sse_initiative.js#L88-L90

Can we change the string _Mutual_ for _Mutual Organisation_ ?

**Comment by ColmMassey** [comment] 2020-12-14 21:24
What is the difference between the argument regorg and orgStructure ?

**Comment by dtmakm27** [comment] 2021-01-06 22:48
> Can we change the string Mutual for Mutual Organisation ?

Added this 



What is the difference between the argument regorg and orgStructure ?

regorg - is only the first organisational structure we have for a particular initiative 
orgStructure - is a list of all organisational structures that we have for a particular initiative

**Comment by ColmMassey** [comment] 2021-01-06 23:27
>    Can we change the string Mutual for Mutual Organisation ?
>Added this

This needs checking on an ICA map.

**Comment by ColmMassey** [comment] 2021-01-13 16:39
Can you update https://dev.ica.solidarityeconomy.coop/ with the latest code so I can test this?

**Comment by ColmMassey** [comment] 2021-01-17 16:30
> Can you update https://dev.ica.solidarityeconomy.coop/ with the latest code so I can test this?

And note the version number here

**Comment by wu-lee** [comment] 2021-01-17 23:15
I've deployed dev.ica using the #dev version of `sea-map`. The `seaMapResolvedVersion` reported here should be ee1d90cb4ffb94d5fdad34e8860b4970e3b2cf45, the commit ID of the tip of `dev`:

https://dev.ica.solidarityeconomy.coop/configuration/version.json

[Snipped: an attempt to explain the reason for the version number not being what you might think, which got lengthy; it's late - probably needs boiling down in daylight.]

**Comment by ColmMassey** [comment] 2021-01-18 14:25
> > Can we change the string Mutual for Mutual Organisation ?
> 
> Added this

Looks like this is another change Dean made which has been lost.

**Comment by wu-lee** [comment] 2021-01-18 16:15
> > > Mutual Organisation ?
> Looks like this is another change Dean made which has been lost.

I can see "Mutual Organisation" in the sea-map code, indeed it's the only match for "Mutual".

Trying to infer how to reproduce this, I read back. Is this one way to do it?

- Visit https://ica.solidarityeconomy.coop/?searchedFields=regorg
- Switch to the search tab in the sidebar, and search for "mutual"
- Scroll down and click on "Taavon Insurance Co."
- The pop-up says it has "Structure Type: Mutual".
- This should be "Structure Type: Mutual Organisation".

**Comment by wu-lee** [comment] 2021-01-18 16:20
Saying that, checking the `standard.csv` file, the *Organiusational Structure* field for Taavon Insurance says simply "Mutual", so I think the pop-up may be merely reflecting what's in the query data.

**Comment by ColmMassey** [comment] 2021-01-18 17:09
The https://dev.ica.solidarityeconomy.coop/ seems to be looking at https://lod.coop/ica

**Comment by ColmMassey** [comment] 2021-01-18 17:23
In the source data, (LOD export members 13 nov 2020.csv)

Taavon Insurance is listed as having _Mutual organisation_ as its _Structure Type_

We map this to 
<essglobal:organisationalStructure rdf:resource='https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/organisational-structure/OS170' />

Which has Definition _Mutual_ but it is one of the exceptions we need to make for ICA, and map it back to _Mutual Organisation_ in the app. So it is visualised as  _Mutual organisation_ in the dialog and when searching using regorg or orgStructure options, this string is what is used.

**Comment by ColmMassey** [comment] 2021-01-18 17:24
I realise that this should be straight forward in the dialog as it probably has several other exceptions, but perhaps there is no mechanism for doing it in the search. :-(

**Comment by ColmMassey** [comment] 2021-01-18 17:25
> I can see "Mutual Organisation" in the sea-map code, indeed it's the only match for "Mutual".

Where?

**Comment by wu-lee** [comment] 2021-01-19 15:17
> The https://dev.ica.solidarityeconomy.coop/ seems to be looking at https://lod.coop/ica

I see what you mean. This is because I deployed the `master` branch of `ica-project` somehow (late night slip-up I guess). 

I've redeployed.

**Comment by wu-lee** [comment] 2021-01-19 15:19
> > I can see "Mutual Organisation" in the sea-map code, indeed it's the only match for "Mutual".
> 
> Where?

Here:
https://github.com/SolidarityEconomyAssociation/sea-map/blob/dev/www/map-app/app/model/sse_initiative.js#L88-L90

**Comment by ColmMassey** [comment] 2021-01-19 15:58
> 
> 
> > The https://dev.ica.solidarityeconomy.coop/ seems to be looking at https://lod.coop/ica
> 
> I see what you mean. This is because I deployed the `master` branch of `ica-project` somehow (late night slip-up I guess).
> 
> I've redeployed.

Great. Oxford is doing the same. See the power of ShipShape!

**Comment by ColmMassey** [comment] 2021-01-19 16:04
But do you agree that it doesn't seem to use it?

**Comment by wu-lee** [comment] 2021-01-19 16:50
> Great. Oxford is doing the same. See the power of ShipShape!

Yes! Oops. I've redeployed that too. We need more automation!

**Comment by wu-lee** [comment] 2021-01-19 16:52
> But do you agree that it doesn't seem to use it?

Not sure of the context here - you mean Oxford isn't using development? If so yes, and I think they're all consistent now (According to ShipShape)

**Comment by wu-lee** [comment] 2021-01-19 17:04
> In the source data, (LOD export members 13 nov 2020.csv)
> 
> Taavon Insurance is listed as having _Mutual organisation_ as its _Structure Type_
> 
> We map this to
> <essglobal:organisationalStructure rdf:resource='https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/organisational-structure/OS170' />
> 
> Which has Definition _Mutual_ but it is one of the exceptions we need to make for ICA, and map it back to _Mutual Organisation_ in the app. So it is visualised as _Mutual organisation_ in the dialog and when searching using regorg or orgStructure options, this string is what is used.

So just to echo this back to check I understand: The normalised data row for Taavon in `standard.csv` *should* have _Mutual_ in the _Organisational Structure_ field (which I gather is how it represents _OS170_), but the sea-map dialog should create the illusion this term is _Mutual Organisation_ (displaying it so and searching for it correctly). Right?

**Comment by ColmMassey** [comment] 2021-01-19 21:42
> So just to echo this back to check I understand: The normalised data row for Taavon in `standard.csv` _should_ have _Mutual_ in the _Organisational Structure_ field (which I gather is how it represents _OS170_), but the sea-map dialog should create the illusion this term is _Mutual Organisation_ (displaying it so and searching for it correctly). Right?

Yes

**Comment by ColmMassey** [comment] 2021-01-19 21:44
> > But do you agree that it doesn't seem to use it?
> 
> Not sure of the context here - you mean Oxford isn't using development? If so yes, and I think they're all consistent now (According to ShipShape)

I was asking you to confirm that the string  _Mutual organisation_ wasn't being used in the ICA search or dialog.

**Comment by wu-lee** [comment] 2021-01-19 23:49
Ok, checking the development version of `ica-project` locally with latest sea-map, when I repeat the steps above for Taavon, I see the correct behaviour: "Structure Type: Mutual Organisation" in the pop up.

What I think has fixed this is that I reviewed the `ica-project` commit history, and straightened it out so that all the work is on the dev branch, then merged to master (preserving production URLs). This seems to have captured something done only on master back into dev - the development branch includes all the work again, as it should. The tidied versions are now `dev` and `master` below, the untidied `retired-dev` and `retired-master`. The tips of the old and new branches are identical, as are the release commits on `master` / `retired-master`, and the whole thing is a bit simpler to follow. I think the missing changes are in `popup.js` which is a custom file in `ica-project` which overrides `sea-map` default behaviour.

![image](https://user-images.githubusercontent.com/67825/105107416-fb7d4680-5aaf-11eb-8c0c-f4838059db78.png)

**Comment by ColmMassey** [comment] 2021-01-20 00:45
Well this addresses the issue I had, so happy to close.

**Closed** 2021-01-29 12:30 UTC
